# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: jhon
      MONGO_INITDB_ROOT_PASSWORD: a123
      MONGO_INITDB_DATABASE: cafe
    ports: 
      - 27017:27017
    volumes: 
      - ./db_scripts/init.js:/docker-entrypoint-initdb.d/init.js
  

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: jhon
      ME_CONFIG_MONGODB_ADMINPASSWORD: a123
    depends_on: 
      - mongo
  
  # pandora:
  #   image: pandorafms/pandorafms:7
  #   ports: 
  #     - 4000:80
